#!/usr/bin/env python3
"""Create a datalake project skeleton.

Usage: python3 scripts/create_datalake_structure.py [--root /path/to/project]
"""
import argparse
from pathlib import Path
import sys

STRUCTURE = {
    "src/datalake": ["__init__.py", "__main__.py"],
    "src/datalake/ingestion": ["__init__.py"],
    "src/datalake/processing": ["__init__.py"],
    "src/datalake/storage": ["__init__.py"],
    "data/raw": ["README.md"],
    "data/staged": ["README.md"],
    "data/curated": ["README.md"],
    "configs": ["config.yaml"],
    "notebooks": ["README.md"],
    "docs": ["README.md"],
    "tests": ["test_sample.py"],
    "scripts": ["README.md"],
    "logs": [".gitkeep"],
    "infra": ["README.md"],
    "pipelines": ["README.md"],
    ".github/workflows": ["python-app.yml"],
    "docker": ["Dockerfile"]
}

FILES = {
    "README.md": "# Datalake project\n\nProject scaffold generated by create_datalake_structure.py\n",
    ".gitignore": "# Python\n__pycache__/\n*.pyc\n.env\n.venv/\n# Data\ndata/*\n!data/.gitkeep\nlogs/\n",
    "pyproject.toml": "[project]\nname = \"datalake\"\nversion = \"0.1.0\"\n\n[build-system]\nrequires = [\"setuptools>=42\"]\nbuild-backend = \"setuptools.build_meta\"\n",
    "requirements.txt": "# Add runtime requirements here\n",
    "Makefile": "init:\n\tpython3 -m venv .venv\n\t.pip install -r requirements.txt\n",
    "scripts/README.md": "Scripts to operate and deploy the datalake.\n",
    "docs/README.md": "Project docs.\n",
    "configs/config.yaml": "# Add config values here\n",
    "src/datalake/__init__.py": "__version__ = \"0.1.0\"\n",
    "src/datalake/__main__.py": "from datalake import __version__\n\nif __name__ == '__main__':\n    print(f'Package datalake version {__version__}')\n",
    "tests/test_sample.py": "def test_placeholder():\n    assert True\n",
    ".github/workflows/python-app.yml": "name: Python package\n\non: [push, pull_request]\n\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v2\n      - name: Set up Python\n        uses: actions/setup-python@v2\n        with:\n          python-version: '3.10'\n      - name: Install dependencies\n        run: pip install -r requirements.txt\n      - name: Run tests\n        run: pytest -q\n",
    "docker/Dockerfile": "FROM python:3.10-slim\nWORKDIR /app\nCOPY . /app\nRUN pip install -r requirements.txt\nCMD [\"python3\", \"-m\", \"datalake\"]\n"
}


def create_structure(root: Path):
    root = root.resolve()
    print(f"Creating datalake skeleton under {root}")

    for folder, files in STRUCTURE.items():
        folder_path = root / folder
        folder_path.mkdir(parents=True, exist_ok=True)
        for fname in files:
            fpath = folder_path / fname
            if not fpath.exists():
                content = """
"""
                if fname.endswith('.py'):
                    content = "# placeholder\n"
                elif fname.endswith('.yml') or fname.endswith('.yaml'):
                    content = "# config file\n"
                elif fname == 'README.md':
                    content = f"# {folder}\n\nPlaceholder.\n"
                fpath.write_text(content)
                print(f"  created {fpath.relative_to(root)}")
            else:
                print(f"  exists {fpath.relative_to(root)}")

    # Write top-level files
    for path, content in FILES.items():
        fpath = root / path
        if not fpath.parent.exists():
            fpath.parent.mkdir(parents=True, exist_ok=True)
        if not fpath.exists():
            fpath.write_text(content)
            print(f"  created {fpath.relative_to(root)}")
        else:
            print(f"  exists {fpath.relative_to(root)}")


def main(argv):
    parser = argparse.ArgumentParser()
    parser.add_argument('--root', default='.', help='Project root to create structure in')
    args = parser.parse_args(argv)
    create_structure(Path(args.root))


if __name__ == '__main__':
    main(sys.argv[1:])
